global_keydown=global_timer=global_cdiv=null;global_init_keyboard=0;var glbl_keys=[],touchinfo={touches:[]};touchinfo.touches[0]={};touchinfo.touches[1]={};touchinfo.touches[2]={};touchinfo.touches[3]={};touchinfo.touches[4]={};touchinfo.touches[5]={};touchinfo.touches[0].pageX=0;touchinfo.touches[0].pageY=0;touchinfo.touches[1].pageX=0;touchinfo.touches[1].pageY=0;touchinfo.touches[2].pageX=0;touchinfo.touches[2].pageY=0;touchinfo.touches[3].pageX=0;touchinfo.touches[3].pageY=0;
touchinfo.touches[4].pageX=0;touchinfo.touches[4].pageY=0;touchinfo.touches[5].pageX=0;touchinfo.touches[5].pageY=0;var mouseinfo={};function INITKEYBOARD(){0==global_init_keyboard&&(document.addEventListener("keydown",function(a){global_keydown=a.keyCode;glbl_keys[a.keyCode]=1},!0),document.addEventListener("keyup",function(a){1==glbl_keys[a.keyCode]&&(glbl_keys[a.keyCode]=0);global_keydown==a.keyCode&&(global_keydown=0)},!0),global_init_keyboard=1)}
function INITMOUSE(){document.addEventListener("mousemove",mouseHandler,!1);document.onmousedown=function(a){mouseinfo.down=1};document.onmouseup=function(a){mouseinfo.down=0}}function mouseHandler(a){mouseinfo.clientX=a.clientX;mouseinfo.clientY=a.clientY;mouseinfo.screenX=a.screenX;mouseinfo.screenY=a.screenY}
function INITTOUCH(){"ontouchstart"in window&&(document.addEventListener("touchstart",touchHandler,!1),document.addEventListener("touchmove",touchHandler,!1),document.addEventListener("touchend",touchHandler,!1),document.addEventListener("touchcancel",touchHandler,!1))}
function INITTOUCHNEW(){document.addEventListener("touchstart",touchHandler,!1);document.addEventListener("touchmove",touchHandler,!1);document.addEventListener("touchend",touchHandler,!1);document.addEventListener("touchcancel",touchHandler,!1)}function LOADSOUND(a){var b={};b.sound=new Audio(a);b.state=0;b.sound.load();return b}function PLAYSOUND(a){a.state=1;a.sound.play()}
function setTouches(a){1==a.touches.length&&(touchinfo.touches[1].pageX=a.touches[0].pageX,touchinfo.touches[1].pageY=a.touches[0].pageY);2==a.touches.length&&(touchinfo.touches[2].pageX=a.touches[1].pageX,touchinfo.touches[2].pageY=a.touches[1].pageY);3==a.touches.length&&(touchinfo.touches[3].pageX=a.touches[2].pageX,touchinfo.touches[3].pageY=a.touches[2].pageY);4==a.touches.length&&(touchinfo.touches[4].pageX=a.touches[3].pageX,touchinfo.touches[4].pageY=a.touches[3].pageY);5==a.touches.length&&
(touchinfo.touches[5].pageX=a.touches[4].pageX,touchinfo.touches[5].pageY=a.touches[4].pageY)}function touchHandler(a){a.preventDefault();switch(a.type){case "touchstart":touchinfo.total=a.touches.length;setTouches(a);break;case "touchmove":setTouches(a);break;case "touchcancel":touchinfo.total=a.touches.length;break;case "touchend":touchinfo.total=a.touches.length}}function GETKEY(){return global_keydown}function KEYSTATE(a){return glbl_keys[a]}
function GETVALID(a){return document.getElementById(a).value.replace(/(<([^>]+)>)/ig,"")}function WINDOWWIDTH(){return window.innerWidth}function WINDOWHEIGHT(){return window.innerHeight}function SCREENHEIGHT(){return screen.availHeight}function SCREENWIDTH(){return screen.availWidth}function TRIGGERMOUSEOVER(a,b){document.getElementById(a).onmouseover=b}function TRIGGERMOUSEDOWN(a,b){document.getElementById(a).onmousedown=b}function TRIGGERMOUSEUP(a,b){document.getElementById(a).onmouseup=b}
function TRIGGERMOUSEOUT(a,b){document.getElementById(a).onmouseout=b}function TRIGGERWINDOWRESIZE(a){window.onresize=a};
